version: '2'

services:

  app:
    build: ./docker/php/
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - "DB_CONNECTION=pgsql"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_DATABASE=laravel"
      - "DB_USERNAME=laravel"
      - "DB_PASSWORD=password"
      - "RUN_UID=1000"
      - "RUN_USER=user"
      - "RUN_GROUP=user"
    links:
      - db

  web:
    build: ./docker/nginx/
    working_dir: /app
    volumes_from:
      - app
    links:
      - app
    ports:
      - 80:80
  
  db:
    image: postgres:11.3
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=laravel"
      - "POSTGRES_USER=laravel"
      - "POSTGRES_PASSWORD=password"
    ports:
      - 5432:5432

volumes:
  dbdata:
